package main

import (
	"fmt"
	"github.com/go-resty/resty/v2"
	"strconv"
	"time"
)

// Autogenerated
type Autogenerated struct {
	Args struct {
		Limit  string `json:"limit"`
		Order  string `json:"order"`
		PageNo string `json:"page_no"`
		Random string `json:"random"`
		Sort   string `json:"sort"`
	} `json:"args"`
	Headers struct {
		Accept         string `json:"Accept"`
		AcceptEncoding string `json:"Accept-Encoding"`
		Authorization  string `json:"Authorization"`
		Host           string `json:"Host"`
		UserAgent      string `json:"User-Agent"`
		XAmznTraceID   string `json:"X-Amzn-Trace-Id"`
	} `json:"headers"`
	Origin string `json:"origin"`
	URL    string `json:"url"`
}

func main() {
	// Create a Resty Client
	client := resty.New()

	resp, _ := client.R().
		SetQueryParams(map[string]string{
			"page_no": "1",
			"limit":   "20",
			"sort":    "name",
			"order":   "asc",
			"random":  strconv.FormatInt(time.Now().Unix(), 10),
		}).
		SetHeader("Accept", "application/json").
		SetAuthToken("BC594900518B4F7EAC75BD37F019E08FBC594900518B4F7EAC75BD37F019E08F").SetResult(&Autogenerated{}).
		Get("https://httpbin.org/get")
	fmt.Println((*resp.Result().(*Autogenerated)).Headers.Accept)
}
